name: first_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  form_field_validator: ^1.1.0
  firebase_core: "^1.7.0"
  firebase_auth: ^3.0.2
  firebase_storage: ^10.0.5
  fluttertoast: ^8.0.8
  syncfusion_flutter_datepicker: ^19.2.57
  intl: ^0.17.0
  flutter_svg: ^0.22.0
  provider: ^6.0.0
  cloud_firestore: "^2.5.3"
  google_fonts: ^2.1.0
  file_picker: ^4.1.3
  syncfusion_flutter_calendar: ^19.3.44
  syncfusion_flutter_core: ^19.3.44
  flutter_local_notifications: ^9.0.0
  flutter_native_timezone: ^1.1.0
  rxdart: ^0.27.1
  location: ^4.3.0
  geolocator: ^7.7.1
  geocoding: ^2.0.1
  shared_preferences: ^2.0.7
  bottom_navy_bar: ^6.0.0
  sqflite: ^2.0.2
  dio: ^4.0.6
  mailer: ^5.0.2

 

 
  
 
dev_dependencies:
  flutter_launcher_icons: ^0.9.1
   
flutter_icons:
  #android: "ic_launcher"
  image_path : "assets/images/emp.png"
  ios: true
  android: true
  #image_path: "assets/logo.jpg"

  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
  - assets/images/
 
  